### ISSUE TITLE
Design architecture for solution

### ISSUE THREAD

**Issue by iprapas** [dima-iot-fog-Optimizer/ml-for-optimizer#24]
You can use a tool like draw.io

**Comment by spapadop** [comment]
![Image of Yaktocat](https://drive.google.com/file/d/1t7B7Dx6vgDB_5Oc-PvZQ8O3uGuIC6cuV/view?usp=sharing)

**Comment by spapadop** [comment]
![Capture](https://user-images.githubusercontent.com/5896507/70549894-3a369280-1b75-11ea-86cb-6c52973906c4.PNG)

**Comment by spapadop** [comment]
![Capture](https://user-images.githubusercontent.com/5896507/70866372-31750080-1f69-11ea-89aa-c71d50a23688.PNG)

**Comment by spapadop** [comment]
![Capture](https://user-images.githubusercontent.com/5896507/72667737-67514d00-3a1f-11ea-81c1-3e35c2e407d1.PNG)

**Comment by spapadop** [comment]
![Capture](https://user-images.githubusercontent.com/5896507/72682975-6b3ea700-3ad3-11ea-98a2-95073a1eb736.PNG)

**Comment by spapadop** [comment]
![Capture](https://user-images.githubusercontent.com/5896507/72683438-b5298c00-3ad7-11ea-9b80-6fbe7f2410d1.PNG)

**Comment by spapadop** [comment]
![Capture](https://user-images.githubusercontent.com/5896507/72683465-dbe7c280-3ad7-11ea-8ef5-620c220b8b60.PNG)
