### ISSUE TITLE
Look into Flink's Metrics API and how we can use it

### ISSUE THREAD

**Issue by ankushs92** [dima-iot-fog-Optimizer/ml-for-optimizer#9]
https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/metrics.html

**Comment by spapadop** [comment]
https://www.slideshare.net/dataArtisans/apache-flink-training-metrics-monitoring

**Comment by ankushs92** [comment]
https://ci.apache.org/projects/flink/flink-docs-stable/internals/task_lifecycle.html

A lot of metrics! Check the info here : https://ci.apache.org/projects/flink/flink-docs-release-1.9/monitoring/metrics.html#registering-metrics
